### ISSUE TITLE
Changing the map

### ISSUE THREAD

**Issue by Strangeeew** [Levak/warfacebot#434]
When I try to change the map, it shows this: Failed to change room settings (8:0). (I gave him the head of the room.)
![1231212](https://user-images.githubusercontent.com/62873715/77886698-612ae880-727a-11ea-9277-f4ec9c05c947.png)

**Comment by Levak** [comment]
Works fine here for me.
What warfacebot version are you using?
A bug was fixed in 1.0.16b 3 months ago:
https://github.com/Levak/warfacebot/releases/tag/1.0.16b

**Comment by Strangeeew** [comment]
I downloaded the latest version, but the error did not disappear.

**Comment by Levak** [comment]
On what map are you running the command? 

Does this work, after login:
```
open tdm_hangar_up
change ptb_D17
```

**Comment by Strangeeew** [comment]
![image](https://user-images.githubusercontent.com/62873715/77935097-0d43f200-72c2-11ea-8e5a-6e4c31e928f0.png)
The /open command works, but the error remains.
The /change command doesn't work on any map.

**Comment by Strangeeew** [comment]
Apparently I found the reason. The bot creates a room with an English name. The fact is that you can't write English letters in the name.

**Comment by Strangeeew** [comment]
I apologize again for my English.

**Comment by Strangeeew** [comment]
When running the /open command, write the name in English. The error is output, but the room is still created

**Comment by Levak** [comment]
> Apparently I found the reason. The bot creates a room with an English name. The fact is that you can't write English letters in the name.

Try changing `wb.cfg` with `g_language= russian` instead, or edit `cfg/lang/english.cfg`, find `default_room_name`.

**Comment by Strangeeew** [comment]
Yes, it didn't help. Tell me please what command to open the room?

**Comment by Levak** [comment]
> Tell me please what command to open the room?

I told you already. `open ptb_D17`

it should display this:
```
CMD# open tdm_hangar_up 
Room ID: 17000281276910828528
Mission:  pvp/tdm_hangar_up (tdm)
Players: 1/32
Joined room room.pvp_pro_5_r101.17000281276910828528@conference.warface
Players: 1/16
CMD# change ptb_D17
Mission:  pvp/ptb_D17 (ptb)
```

Are you **sure** to be using 1.0.16b? That version specifically fixes this error.

**Comment by Strangeeew** [comment]
I don't want to create a room, I want to open it for other players.

I download these 2 files. From the windows version, I copy 3 files: readline5.dll, wb.exe and zlib1.dll.
![image](https://user-images.githubusercontent.com/62873715/77937074-dae7c400-72c4-11ea-9357-4aa15b5c22de.png)
![image](https://user-images.githubusercontent.com/62873715/77937114-ecc96700-72c4-11ea-81d0-89493b44c7ab.png)

**Comment by Strangeeew** [comment]
When I enter the /open map command, then the room is created with an error and /change does not work. When I enter the /open lms_mojave command, then the room is created with an error, but the /change command works. However, when creating an lms_mojave room, it closes and you can only enter by invitation.
